
export const GOOGLE_ACCOUNTS_URL = process.env.REACT_APP_GOOGLE_ACCOUNTS_URL;
export const GOOGLE_OAUTH_REDIRECT = process.env.REACT_APP_GOOGLE_OAUTH_REDIRECT;
export const GOOGLE_CLIENT_ID = process.env.REACT_APP_GOOGLE_CLIENT_ID;
export const GOOGLE_CLIENT_SECRET = process.env.REACT_APP_GOOGLE_CLIENT_SECRET;
